### ISSUE TITLE
CJK ime input

### ISSUE THREAD

**Issue by 100seungho** [rationalmatter/Juno-Issue-Tracker#116]
Hello from Korea, 
Currently working with juno on my iPad is so much pleasant, still Korean ime input seem bad for me. 
OS: iPadOS 13.2
Device: 2017 iPad Pro 2 (10.5 inch)

**Comment by 100seungho** [comment]
This is how’s it look on **Juno**
![IMG_2318](https://user-images.githubusercontent.com/42087222/71717318-10fae080-2e5b-11ea-9dd0-38c66d3a4617.jpeg)

And this is how’s it should be look like (it’s on Pythonista)
![IMG_2319](https://user-images.githubusercontent.com/42087222/71717323-16f0c180-2e5b-11ea-92ea-d3d8d93b622f.jpeg)

**Comment by navoshta** [comment]
@100seungho does this happen for all text input in Juno, i.e. in both markdown and code cells? I'm assuming this is supposed to be replaced automatically as you type? I thought this has been fixed in iOS 13, could it be related to https://github.com/rationalmatter/Juno-Issue-Tracker/issues/27 perhaps?

**Comment by 100seungho** [comment]
No, same problem appears both in markdown and text cells too. So I don’t think this kind of problem is related to iOS13 update. I looked up things and it’s related to NFD encoding. I know NFD is also standard protocol, but NFD encoding makes Korean synonyms and antonyms to be seperated.

**Comment by navoshta** [comment]
Hmm thanks @100seungho — perhaps it's a separate issue from #27 then. Could you please make a screen recording of how it's supposed to work (e.g. in some other app)? I'm assuming this is handled on the iOS level of text input, but I could be missing something.

**Comment by alexstaravoitau** [comment]
Korean IME input has been improved in the last TestFlight build of Juno (1.3.12) — it's still not ideal, but I *think* it's as far as I can improve it until the actual issue in the CodeMirror is fixed (see https://github.com/codemirror/CodeMirror/issues/3137). 

If you're not on TestFlight and would like to help test it, ping me at beta@juno.sh.

**Comment by alexstaravoitau** [comment]
Moving discussion to #135, as Korean seems to be the only language input not fully working in recent releases of iOS/iPadOS.
