### ISSUE TITLE
Korean issue

### ISSUE THREAD

**Issue by pkuk** [rationalmatter/Juno-Issue-Tracker#135]
When entering Korean, the following problems occur

Normal result : “한국어 입력이 이상해요”

> Juno for jupyter

`print('ㅎㅏㄴㄱㅜㄱㅇㅓ ㅇㅣㅂㄹㅕㄱㅇㅣ ㅇㅣㅅㅏㅇㅎㅐㅇㅛ') `

**Comment by navoshta** [comment]
Thanks for reporting @pkuk — looks like it's a duplicate of #116? Also, could you please confirm it's reproducible on iOS 13, i.e. not related to #27?

Finally, if you could please make a recording of how it's supposed to work / how it actually works, that would help a lot — but I'll look into this regardless. Was hoping that those kind of issues got fixed with the iOS 13 update, but apparently not all of them. 😔

**Comment by JaeungHyun** [comment]
@navoshta 
Here i recorded that problem.
I hope it can be fixed soon :)

https://youtu.be/bJRJpvSHJzo

**Comment by draco67p** [comment]
same issue.

**Comment by draco67p** [comment]
https://youtu.be/21S1TTFUvOE
here is more information.

> Thanks for reporting @pkuk — looks like it's a duplicate of #116? Also, could you please confirm it's reproducible on iOS 13, i.e. not related to #27?
> 
> Finally, if you could please make a recording of how it's supposed to work / how it actually works, that would help a lot — but I'll look into this regardless. Was hoping that those kind of issues got fixed with the iOS 13 update, but apparently not all of them. 😔

**Comment by JaeungHyun** [comment]
![image](https://user-images.githubusercontent.com/17588101/127480572-d566890c-8cd2-4d21-939c-f1bdfd0d0c94.png)![image](https://user-images.githubusercontent.com/17588101/127480593-4c975aef-6ca2-4799-91fe-d339e2e39822.png)

Hello again.

I think it may be jupyter's problem..

In native UI(?), input korean is fine.

**Comment by alexstaravoitau** [comment]
@JaeungHyun — yes, looks like it's one of the internal component Jupyter is using. I was hoping this would get fixed with the recent release, where I've updated a bunch of internal components, including those that Jupyter relies on. But sadly looks like it's still there. Apologies it's taking so long, I do hope to get to it soon.

**Comment by alexstaravoitau** [comment]
Korean IME input has been improved in the last TestFlight build of Juno (1.3.12) — it's still not ideal, but I *think* it's as far as I can improve it until the actual issue in the CodeMirror is fixed (see https://github.com/codemirror/CodeMirror/issues/3137). 

If you're not on TestFlight and would like to help test it, ping me at beta@juno.sh.

**Comment by alexstaravoitau** [comment]
Korean IME input workaround has been released to App Store with Juno 1.3.14 and Juno Connect 1.6.9. As mentioned previously, this is likely as far as it can be improved until the underlying issue in CodeMirror is fixed. I'll leave this ticket open for a short while, in an (unlikely) case that my workaround has made things worse or have broken something else.

**Comment by JaeungHyun** [comment]
@navoshta https://user-images.githubusercontent.com/17588101/136780735-55230ae9-f2f0-4a5f-99de-8a0383441017.MOV

Still have some problem :(

**Comment by alexstaravoitau** [comment]
@JaeungHyun Apologies, I don't understand Korean and have very little knowledge about Korean characters — is the problem that while deleting characters it does not correctly delete the "part" of the character, deleting the character completely instead?

**Comment by JaeungHyun** [comment]
@navoshta I think when I type space,  previous character is duplicated.

when deleting, I think it is fine

**Comment by alexstaravoitau** [comment]
@JaeungHyun Ah OK, I see — I'll leave this ticket open and will look into the duplicated characters, but frankly I'm not sure if I will be able to tackle this any further. 😔 Hopefully, someone with the knowledge of Korean IME and JS can come up with a better workaround for CodeMirror 5, and I'll be happy to incorporate it into Juno.
