### ISSUE TITLE
Coloring in Pandas DataFrame no longer working

### ISSUE THREAD

**Issue by lmatute** [rationalmatter/Juno-Issue-Tracker#276]
The coloring of columns in a pandas dataframe no longer works with the latest update. This used to work fine before:

Example:

import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(0, 100, size=(5, 4)), columns=list("ABCD"))
df.style.background_gradient(cmap="Blues")

**Comment by alexstaravoitau** [comment]
Thank you for reporting @lmatute, I will look into this. There has been few slight changes in how Pandas data frames are rendered, probably this is what broke the coloring.

**Comment by alexstaravoitau** [comment]
This should be fixed in the latest Juno and Juno Connect updates. Feel free to reopen or submit a new ticket if there are still some use cases I've missed.

**Comment by lmatute** [comment]
It is fixed. Great work ! 

Luis

**Comment by lmatute** [comment]
Today I came across a different but perhaps related issue with coloring pandas dataframes. In replicating an example in  the pandas documentation I had an error described in the attached notebook. 

Hope you can help 

Luis

**Comment by alexstaravoitau** [comment]
Hi @lmatute — could you open a new ticket? And please make sure to attach a code example or a notebook where I can reproduce the issue, this would help immensely.

**Comment by lmatute** [comment]
For your consideration:

Have you considered opening Tinkerstellar so that authors can directly make their tutorials? The combination of Python and the topic indexing make it an improvement to the flat notebook interface.

I for one would pay top dollars for such an application


Thanks,

Luis

**Comment by alexstaravoitau** [comment]
Hi @lmatute — yes absolutely, this is a somewhat longer-term plan for Tinkerstellar. I'm still not 100% sure in which form this will make its way into the app, but I'm fairly certain it *will* sooner or later (don't have any ETA I'm afraid).
